[package]
name = "sim-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
sim-model.workspace = true
rand_chacha = "0.10.0"
rand_core = "0.10.1"

[lints]
workspace = true

[dev-dependencies]
diffsol = "0.17.1"
