"""Independent Python reference model of the BLDC/PMSM drive (spec: docs/docs/physics)."""

from .params import (
    Action,
    BusParams,
    CtrlParams,
    FocParams,
    GearboxParams,
    InverterParams,
    LoadParams,
    MechParams,
    MitParams,
    MotorParams,
    OpenLoopParams,
    RefParams,
    SimParams,
    SixStepParams,
    SupplyParams,
    ThermalParams,
    ke_from_lambda,
    kt_from_lambda,
    lambda_m_from_kv,
)
from .simulate import simulate

__all__ = [
    "Action",
    "BusParams",
    "CtrlParams",
    "FocParams",
    "GearboxParams",
    "InverterParams",
    "LoadParams",
    "MechParams",
    "MitParams",
    "MotorParams",
    "OpenLoopParams",
    "RefParams",
    "SimParams",
    "SixStepParams",
    "SupplyParams",
    "ThermalParams",
    "ke_from_lambda",
    "kt_from_lambda",
    "lambda_m_from_kv",
    "simulate",
]
