[package]
name = "bldc-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sim-api.workspace = true
clap.workspace = true
parquet = { version = "60.0.0", default-features = false, features = ["arrow", "snap"] }
serde_json = "1.0.151"
serde-saphyr = "1.3.0"
sha2 = "0.11.0"
arrow-array = "60"
arrow-schema = "60"
sim-core.workspace = true
serde = { workspace = true, features = ["derive"] }
anyhow.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true
